_comment: statnett doesn't work. See for example 2018-05-14 which is off by a factor
  two
capacity:
  - -2095
  - 2145
lonlat:
  - 12.254138
  - 61.008235
parsers:
  exchange: ENTSOE.fetch_exchange
  exchangeForecast: ENTSOE.fetch_exchange_forecast
rotation: 90
