bounding_box:
- - 11.492425171000093
  - 60.280991513822045
- - 21.486074487958014
  - 66.78799631800014
parsers:
  consumption: ENTSOE.fetch_consumption
  consumptionForecast: ENTSOE.fetch_consumption_forecast
  generationForecast: ENTSOE.fetch_generation_forecast
  price: ENTSOE.fetch_price
  productionPerModeForecast: ENTSOE.fetch_wind_solar_forecasts
timezone: null
